[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
address = "localhost"
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
